application: visor-perfiles-ka
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  
- url: /static_viewer
  static_dir: static_viewer
  
- url: /admin/interactive|/admin/interactive/execute
  script: google.appengine.ext.admin.application
  login: admin
  
- url: /admin/.*
  script: main.app
  login: admin

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.1"
  
- name: numpy
  version: "1.6.1"
  
builtins:
- remote_api: on

admin_console:
  pages:
    - name: Interactive Console
      url: /admin/interactive